import React, { useEffect, useRef, useState } from 'react';
import { useTheme } from '../context/ThemeContext';

interface WasmPlayerProps {
  gameId: string;
  assetCount?: number;
}

// Extend global window for Emscripten Module
declare global {
  interface Window {
    Module: any;
  }
}

const WasmPlayer: React.FC<WasmPlayerProps> = ({ gameId, assetCount = 0 }) => {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [consoleOutput, setConsoleOutput] = useState<string[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const { theme } = useTheme();

  const addLog = (msg: string) => {
    setConsoleOutput(prev => [...prev.slice(-6), msg]);
  };

  useEffect(() => {
    setConsoleOutput([]);
    setIsLoading(true);
    setError(null);

    // Initial logs to show activity
    addLog(`> Initializing ${gameId} runtime...`);
    if (assetCount > 0) addLog(`> Preparing to fetch ${assetCount} asset chunks...`);

    // 1. Create the Emscripten Module configuration
    window.Module = {
      canvas: canvasRef.current,
      print: (text: string) => addLog(text),
      printErr: (text: string) => console.error(text),
      onRuntimeInitialized: () => {
        addLog("> Binary execution started.");
        setIsLoading(false);
      },
      setStatus: (text: string) => {
        if (text) addLog(`> ${text}`);
      },
      locateFile: (path: string) => {
        return `/games/${path}`;
      }
    };

    // 2. Dynamically load the JS glue code generated by Emscripten
    const script = document.createElement('script');
    script.src = `/games/${gameId}.js`;
    script.async = true;

    script.onload = () => {
        addLog(`> Interface loaded: ${gameId}.js`);
    };

    script.onerror = () => {
        setError(`Failed to load game binary: /games/${gameId}.js. Ensure the game is compiled and pushed to GitHub.`);
        setIsLoading(false);
    };

    document.body.appendChild(script);

    return () => {
        // Cleanup: Remove script and stop any active game loops if possible
        document.body.removeChild(script);
        if (window.Module && window.Module.abort) {
            window.Module.abort();
        }
        delete window.Module;
    };
  }, [gameId, theme]);

  return (
    <div className={`relative w-full aspect-video rounded-xl overflow-hidden shadow-2xl transition-colors duration-300 scanlines ${theme === 'light' ? 'bg-white' : 'bg-black border border-white/5'}`}>
        {/* The Real Game Canvas */}
        <canvas 
            ref={canvasRef} 
            id="canvas" // Emscripten often looks for id="canvas"
            className="w-full h-full object-contain block touch-none"
            onContextMenu={(e) => e.preventDefault()}
        />

        {/* Loading Overlay */}
        {isLoading && (
            <div className={`absolute inset-0 flex flex-col items-center justify-center z-10 backdrop-blur-md ${theme === 'light' ? 'bg-white/80' : 'bg-black/90'}`}>
                <div className={`w-12 h-12 border-[3px] rounded-full animate-spin mb-4 ${theme === 'light' ? 'border-slate-100 border-t-blue-600' : 'border-white/5 border-t-void-accent'}`}></div>
                <div className={`font-black text-[10px] uppercase tracking-[0.3em] animate-pulse ${theme === 'light' ? 'text-blue-600' : 'text-void-accent'}`}>
                    {theme === 'light' ? 'Initializing Divine Code' : 'Accessing High-Frequency Memory'}
                </div>
            </div>
        )}

        {/* Error State */}
        {error && (
            <div className="absolute inset-0 flex flex-col items-center justify-center z-20 bg-black/90 p-6 text-center">
                <div className="text-red-500 font-bold mb-4">ENGINE_LOAD_FAILURE</div>
                <div className="text-gray-400 text-xs font-mono max-w-md">{error}</div>
                <button 
                    onClick={() => window.location.reload()}
                    className="mt-6 px-6 py-2 bg-white/10 hover:bg-white/20 rounded text-[10px] uppercase font-bold tracking-widest transition-all"
                >
                    Retry Initialization
                </button>
            </div>
        )}

        {/* Terminal Console */}
        <div className="absolute bottom-0 left-0 p-4 w-full pointer-events-none z-10">
            <div className={`font-mono text-[10px] p-3 rounded-lg shadow-2xl max-w-[320px] backdrop-blur-xl border transition-all ${theme === 'light' ? 'bg-white/40 text-blue-800 border-white' : 'bg-black/60 text-void-accent border-white/5'}`}>
                {consoleOutput.map((line, i) => (
                    <div key={i} className="leading-relaxed opacity-90">{line}</div>
                ))}
                {!isLoading && !error && <div className="animate-pulse inline-block w-1.5 h-3 bg-current align-middle ml-1"></div>}
            </div>
        </div>
        
        {/* Decorative corner accents */}
        <div className={`absolute top-4 left-4 w-4 h-4 border-l-2 border-t-2 opacity-30 ${theme === 'light' ? 'border-blue-600' : 'border-void-accent'}`}></div>
        <div className={`absolute top-4 right-4 w-4 h-4 border-r-2 border-t-2 opacity-30 ${theme === 'light' ? 'border-blue-600' : 'border-void-accent'}`}></div>
        <div className={`absolute bottom-4 left-4 w-4 h-4 border-l-2 border-b-2 opacity-30 ${theme === 'light' ? 'border-blue-600' : 'border-void-accent'}`}></div>
        <div className={`absolute bottom-4 right-4 w-4 h-4 border-r-2 border-b-2 opacity-30 ${theme === 'light' ? 'border-blue-600' : 'border-void-accent'}`}></div>
    </div>
  );
};

export default WasmPlayer;